require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FormulaeController do

  def mock_formula(stubs={})
    @mock_formula ||= mock_model(Formula, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all formulae as @formulae" do
      Formula.stub(:all) { [mock_formula] }
      get :index
      assigns(:formulae).should eq([mock_formula])
    end
  end

  describe "GET show" do
    it "assigns the requested formula as @formula" do
      Formula.stub(:find).with("37") { mock_formula }
      get :show, :id => "37"
      assigns(:formula).should be(mock_formula)
    end
  end

  describe "GET new" do
    it "assigns a new formula as @formula" do
      Formula.stub(:new) { mock_formula }
      get :new
      assigns(:formula).should be(mock_formula)
    end
  end

  describe "GET edit" do
    it "assigns the requested formula as @formula" do
      Formula.stub(:find).with("37") { mock_formula }
      get :edit, :id => "37"
      assigns(:formula).should be(mock_formula)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created formula as @formula" do
        Formula.stub(:new).with({'these' => 'params'}) { mock_formula(:save => true) }
        post :create, :formula => {'these' => 'params'}
        assigns(:formula).should be(mock_formula)
      end

      it "redirects to the created formula" do
        Formula.stub(:new) { mock_formula(:save => true) }
        post :create, :formula => {}
        response.should redirect_to(formula_url(mock_formula))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved formula as @formula" do
        Formula.stub(:new).with({'these' => 'params'}) { mock_formula(:save => false) }
        post :create, :formula => {'these' => 'params'}
        assigns(:formula).should be(mock_formula)
      end

      it "re-renders the 'new' template" do
        Formula.stub(:new) { mock_formula(:save => false) }
        post :create, :formula => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested formula" do
        Formula.stub(:find).with("37") { mock_formula }
        mock_formula.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :formula => {'these' => 'params'}
      end

      it "assigns the requested formula as @formula" do
        Formula.stub(:find) { mock_formula(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:formula).should be(mock_formula)
      end

      it "redirects to the formula" do
        Formula.stub(:find) { mock_formula(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(formula_url(mock_formula))
      end
    end

    describe "with invalid params" do
      it "assigns the formula as @formula" do
        Formula.stub(:find) { mock_formula(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:formula).should be(mock_formula)
      end

      it "re-renders the 'edit' template" do
        Formula.stub(:find) { mock_formula(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested formula" do
      Formula.stub(:find).with("37") { mock_formula }
      mock_formula.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the formulae list" do
      Formula.stub(:find) { mock_formula }
      delete :destroy, :id => "1"
      response.should redirect_to(formulae_url)
    end
  end

end
