require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PortfoliosController do

  def mock_portfolio(stubs={})
    @mock_portfolio ||= mock_model(Portfolio, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all portfolios as @portfolios" do
      Portfolio.stub(:all) { [mock_portfolio] }
      get :index
      assigns(:portfolios).should eq([mock_portfolio])
    end
  end

  describe "GET show" do
    it "assigns the requested portfolio as @portfolio" do
      Portfolio.stub(:find).with("37") { mock_portfolio }
      get :show, :id => "37"
      assigns(:portfolio).should be(mock_portfolio)
    end
  end

  describe "GET new" do
    it "assigns a new portfolio as @portfolio" do
      Portfolio.stub(:new) { mock_portfolio }
      get :new
      assigns(:portfolio).should be(mock_portfolio)
    end
  end

  describe "GET edit" do
    it "assigns the requested portfolio as @portfolio" do
      Portfolio.stub(:find).with("37") { mock_portfolio }
      get :edit, :id => "37"
      assigns(:portfolio).should be(mock_portfolio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created portfolio as @portfolio" do
        Portfolio.stub(:new).with({'these' => 'params'}) { mock_portfolio(:save => true) }
        post :create, :portfolio => {'these' => 'params'}
        assigns(:portfolio).should be(mock_portfolio)
      end

      it "redirects to the created portfolio" do
        Portfolio.stub(:new) { mock_portfolio(:save => true) }
        post :create, :portfolio => {}
        response.should redirect_to(portfolio_url(mock_portfolio))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portfolio as @portfolio" do
        Portfolio.stub(:new).with({'these' => 'params'}) { mock_portfolio(:save => false) }
        post :create, :portfolio => {'these' => 'params'}
        assigns(:portfolio).should be(mock_portfolio)
      end

      it "re-renders the 'new' template" do
        Portfolio.stub(:new) { mock_portfolio(:save => false) }
        post :create, :portfolio => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portfolio" do
        Portfolio.stub(:find).with("37") { mock_portfolio }
        mock_portfolio.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :portfolio => {'these' => 'params'}
      end

      it "assigns the requested portfolio as @portfolio" do
        Portfolio.stub(:find) { mock_portfolio(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:portfolio).should be(mock_portfolio)
      end

      it "redirects to the portfolio" do
        Portfolio.stub(:find) { mock_portfolio(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(portfolio_url(mock_portfolio))
      end
    end

    describe "with invalid params" do
      it "assigns the portfolio as @portfolio" do
        Portfolio.stub(:find) { mock_portfolio(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:portfolio).should be(mock_portfolio)
      end

      it "re-renders the 'edit' template" do
        Portfolio.stub(:find) { mock_portfolio(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portfolio" do
      Portfolio.stub(:find).with("37") { mock_portfolio }
      mock_portfolio.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the portfolios list" do
      Portfolio.stub(:find) { mock_portfolio }
      delete :destroy, :id => "1"
      response.should redirect_to(portfolios_url)
    end
  end

end
